# Generated by Django 5.2.7 on 2025-11-21 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cadastrocliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluido'), ('agendado', 'Agendado'), ('esperando_pecas', 'Esperando Peças')], default='em_andamento', max_length=20)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('cor', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cadastrocliente')),
            ],
        ),
    ]
