# Generated by Django 5.2.7 on 2025-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluido'), ('agendado', 'Agendado'), ('esperando_pecas', 'Esperando Peças')], default='agendado', max_length=20),
        ),
    ]
