# Generated by Django 5.2.7 on 2025-11-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cadastrocliente_cpf'),
        ('veiculos', '0002_alter_veiculo_placa_alter_veiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cadastrocliente'),
        ),
    ]
