# Generated by Django 5.2.7 on 2025-12-09 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cadastrocliente_cpf'),
        ('veiculos', '0003_alter_veiculo_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='clientes.cadastrocliente'),
        ),
    ]
