# Generated by Django 5.2.7 on 2025-12-09 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cadastrocliente_cpf'),
        ('veiculos', '0004_veiculo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='clientes.cadastrocliente'),
        ),
    ]
