# Generated by Django 5.2.7 on 2025-12-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_remove_veiculo_cliente_alter_veiculo_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='status',
        ),
    ]
