# Generated by Django 5.2.7 on 2025-12-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cadastrocliente_cpf'),
        ('veiculos', '0005_remove_veiculo_cliente_alter_veiculo_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadrastroServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Troca de óleo', 'Troca de óleo'), ('Troca de filtros', 'Troca de filtros'), ('Revisão', 'Revisão'), ('Alinhamento e balanceamento', 'Alinhamento e balanceamento'), ('Freios', 'Freios'), ('Suspensão', 'Suspensão'), ('Troca de pneus', 'Troca de pneus'), ('Ar-condicionado', 'Ar-condicionado'), ('Elétrica', 'Elétrica'), ('Diagnóstico eletrônico', 'Diagnóstico eletrônico'), ('Correias', 'Correias'), ('Embreagem', 'Embreagem'), ('Motor e câmbio', 'Motor e câmbio')], max_length=50)),
                ('mecanico', models.CharField(blank=True, max_length=100, null=True)),
                ('data_agendamento', models.DateField()),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cadastrocliente')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
        ),
    ]
