# Generated by Django 5.2.7 on 2025-12-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrastroservicos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
