# Generated by Django 5.2.7 on 2025-12-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_cadrastroservicos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrastroservicos',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Normal', 'Normal'), ('Alta', 'Alta')], default='Normal', max_length=20),
        ),
    ]
