# Generated by Django 5.2.7 on 2025-12-10 23:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_cadrastroservicos_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
