# Generated by Django 5.2.7 on 2025-12-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_cadrastroservicos_valor'),
        ('veiculos', '0006_remove_veiculo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadrastroservicos',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo'),
        ),
    ]
