# Generated by Django 5.2.7 on 2026-01-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_remove_cadrastroservicos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='prioridade',
            field=models.CharField(choices=[('3', 'Baixa'), ('2', 'Normal'), ('1', 'Alta')], default='Normal', max_length=20),
        ),
    ]
