# Generated by Django 5.2.7 on 2026-01-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_alter_cadrastroservicos_prioridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadrastroservicos',
            options={'ordering': ['prioridade', '-data_agendamento']},
        ),
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='prioridade',
            field=models.CharField(choices=[(3, 'Baixa'), (2, 'Normal'), (1, 'Alta')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='status',
            field=models.CharField(choices=[(1, 'Pendente'), (2, 'Em andamento'), (3, 'Concluído')], default='Pendente', max_length=20),
        ),
    ]
