# Generated by Django 5.2.7 on 2026-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_alter_cadrastroservicos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='prioridade',
            field=models.IntegerField(choices=[(3, 'Baixa'), (2, 'Normal'), (1, 'Alta')], default=2),
        ),
        migrations.AlterField(
            model_name='cadrastroservicos',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Em andamento'), (3, 'Concluído')], default=1),
        ),
    ]
